[package]
name = "rust_rbf_kan"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-nn={version="0.6.0"}
candle = {package = "candle-core", version = "0.6.0" }
candle-datasets = { version="0.6"}
candle-einops = "0.1.2"
